### ISSUE TITLE
The software does not run on Windows 64bit

### ISSUE THREAD

**Issue by karbalaee20** [berkayalcin/BigBlueButton-Downloader#2]
dear dr.Berkay YALÇIN
I ran the program in Windows 64bit.
  But after opening the program;
  It closed and did not open.
Why?
![1](https://user-images.githubusercontent.com/77395400/107763575-15731780-6d44-11eb-899e-9d23fa836d7f.png)
![2](https://user-images.githubusercontent.com/77395400/107763580-16a44480-6d44-11eb-8272-ff60d8cf9a20.png)

**Comment by berkayalcin** [comment]
Hi @karbalaee20 ,
Please run program as following.
```shell
./BigBlueButton-Video-Downloader download --help
```
If you get error on runtime based on Selenium, please change chromedriver with windows version.

**Comment by karbalaee20** [comment]
thank you
I tested.
I typed the code the way you said. But it was closed.about the sentence"please change chromedriver with windows version."
I didn't notice
code:
  
 ./BigBlueButton-Video-Downloader download-m true \
I entered the link instead:https://playback.url
 ./BigBlueButton-Video-Downloader download -u https://playback.url \
 
 ./BigBlueButton-Video-Downloader download -o test \
 ./BigBlueButton-Video-Downloader download -d /Users\ASUS\Desktop\Windows64/ \
 ./BigBlueButton-Video-Downloader download -w true \
 ./BigBlueButton-Video-Downloader download -v true \ 
 ./BigBlueButton-Video-Downloader download -p true

**Comment by berkayalcin** [comment]
Yes, you can download chromedriver file from https://chromedriver.chromium.org/ and change the chromedriver file in solution.

**Comment by karbalaee20** [comment]
Thank you for your help
Please watch the video 

https://user-images.githubusercontent.com/77395400/108060669-6a789b80-706c-11eb-8367-e74c3404bdfe.mp4

**Comment by berkayalcin** [comment]
Please put the new chromedriver into solution folder, then pass all required option to BigBlueButton-Downloader

**Comment by berkayalcin** [comment]
![image](https://user-images.githubusercontent.com/5766537/108069984-0c9c8180-7075-11eb-9230-d3524418b238.png)
You need replace chromedriver in project with the newest one.

**Comment by karbalaee20** [comment]
Thank you for your help
excuse me.
This is my last request
Where is the solution folder,?
please, Can you make an example video?
thanks

**Comment by axoxolotl** [comment]
Hi, I tried using your program on Windows 10 Home (Version 2004) with .NET Core 3.1. 
The program starts normally and works until after "==ResizingComponents", then it throws an unhandled exception for a 404. 
The input link is confirmed working. 
Screenshots of the problem: 
![image](https://user-images.githubusercontent.com/79226897/108325657-978e9080-71c9-11eb-83a0-70eabb9a8445.png)

![image](https://user-images.githubusercontent.com/79226897/108325598-80e83980-71c9-11eb-8be7-f5c18cc40cf8.png)

**Comment by berkayalcin** [comment]
Okey, I will add a tutorial video for batch and single download in this week. Thanks for your feedback.

**Comment by karbalaee20** [comment]
Hi @berkayalcin 
I am waiting for your response.
Thanks.

**Comment by berkayalcin** [comment]
### Single Download

- Open Terminal
- Jump to BigBlueButton-Downloader folder
- Change chromedriver which in root folder from https://chromedriver.chromium.org/ if your os not macOS.
- Run this command with your parameters.
```csharp
 ./BigBlueButton-Video-Downloader \
 -m true \
 -u https://playback.url \
 -o outputFileName \
 -d /Users/berkay/Desktop/TestDirectory/ \
 -w true \
 -v true \ 
 -p true
```

**Comment by sedat-54** [comment]
İyi akşamlar
Çalışmanız için teşekkürler. Ekteki dosyadaki şekilde indirme hatası alıyorum. Sanıyorum framerate ile ilgili. Bizim üniversitenin ayarlarından mı kaynaklı acaba?
[hata ekrani.txt](https://github.com/berkayalcin/BigBlueButton-Downloader/files/6057828/hata.ekrani.txt)
